### ISSUE TITLE
deps.js与jquery.form插件冲突

### ISSUE THREAD

**Issue by ZhangPengPaul** [TBEDP/datavjs#132]
deps.js与jquery.form插件冲突，执行jquery.form中的ajaxform或ajaxsubmit时在deps中总是会报no method [ajaxform]或[ajaxsubmit]。

**Comment by JacksonTian** [comment]
应该是DataV中的jQuery与你的jquery.form冲突了。可以将DataV中的jQuery移除掉，用你们项目的jQuery就行。

**Comment by JacksonTian** [comment]
你可以描述下你项目的依赖情况
- 支持IE6？
- 兼容IE678？
- 有jQuery？
- 有Underscore？

**Comment by ZhangPengPaul** [comment]
我只是导入deps.js,datav.js和某个chart，这样也会冲突么？datav中的jq在什么位置？

**Comment by ZhangPengPaul** [comment]
兼容ie7+,有jq

**Comment by JacksonTian** [comment]
用 https://github.com/TBEDP/datavjs/blob/master/build/datav_without_jquery_json.js 吧，这个打包去除了jQuery和JSON2.js
