### ISSUE TITLE
很久没更新消息了

### ISSUE THREAD

**Issue by guarder** [TBEDP/datavjs#144]
很久没看到更新了，是否几位老大在酝酿大版本？还是。。。

**Comment by xibei** [comment]
实在不好意思，最近工作比较忙，是有一阵子没有更新了。接下来等手头的工作告一段落，我们会把最近这段时间的一些成果整合进datav.js  

## 

xibei
已使用 Sparrow (http://www.sparrowmailapp.com/?sig)

在 2013年12月23日 星期一，下午8:08，xingwei 写道：

**Comment by guarder** [comment]
赞
