### ISSUE TITLE
柳岩离幸福好远

### ISSUE THREAD

**Issue by fengmk2** [TBEDP/datavjs#16]
force 图距离计算有bug。

![http://ww4.sinaimg.cn/large/6cfc7910jw1dxshqcnc7hj.jpg](http://ww4.sinaimg.cn/large/6cfc7910jw1dxshqcnc7hj.jpg)

**Comment by JacksonTian** [comment]
这个路径是随机算出来的丫

**Comment by theseue** [comment]
这BUG提的，标题太有水平了。本身不会这么远的，但是因为不能有动画，我在计算到一半的时候就让计算停止了，否则还要算好久才能出来，所以还没有运动到准确位置。我再优化看看
