### ISSUE TITLE
地图会重复下载JSON数据

### ISSUE THREAD

**Issue by JacksonTian** [TBEDP/datavjs#95]
最好存放在一个静态的变量上。不要存在实例上。因为实例可能会重复创建

**Comment by jdk137** [comment]
“存在实例”怎么理解?

在 2012年12月14日 上午5:26，Jackson Tian notifications@github.com写道：

**Comment by JacksonTian** [comment]
你放在this的cache上的。我new一个新map就不能用已下载的数据了。会导致重新下载JSON文件
